void		_adjust(SV* self,NV l,NV sigma,AV* unit,AV* v);
void		_array_DESTROY(SV* obj);
SV*		_array_FETCH(SV* self,I32 y);
IV		_array_FETCHSIZE(SV* self);
void		_array_STORE(SV* self,IV y,SV* aref);
int		_array_refcount(SV* self);
void		_bmu(SV* self, AV* sample);
void		_bmu_guts(SOM_GENERIC *generic,AV *sample,IV *bx,IV *by,NV *bd);
SV*		_hexa_FETCH(SV* self,SV* key);
void		_hexa_STORE(SV* self,SV* key,SV* val);
NV		_hexa_distance(NV x1,NV y1,NV x2,NV y2);
AV*		_hexa_neighbors(SV* self,double sigma,double X,double Y);
void		_hexa_new(const char* class);
SOM_Array*		_make_array(SOM_Map* map);
SOM_Map*		_make_map(SOM_GENERIC *generic);
SOM_Vector*		_make_vector(SOM_Array* array);
void		_map_DESTROY(SV* obj);
SV*		_map_FETCH(SV* self,I32 x);
IV		_map_FETCHSIZE(SV* self);
int		_map_refcount(SV* self);
void		_rect_DESTROY(SV* obj);
SV*		_rect_FETCH(SV* self,SV* key);
SV*		_rect_STORE(SV* self,SV* key,SV* val);
AV*		_rect_neighbors(SV* self,double sigma,double X,double Y,...);
void		_rect_new(const char* class,...);
SV*		_rect_radius(SV* self);
int		_rect_refcount(SV* self);
void		_som_train(SV* self);
AV*		_torus_neighbors(SV* self,NV sigma,NV X,NV Y);
void		_vector_DESTROY(SV* obj);
SV*		_vector_FETCH(SV* self,I32 z);
IV		_vector_FETCHSIZE(SV* self);
void		_vector_STORE(SV* self, I32 z, double val);
NV		_vector_distance(AV* V1, AV* V2);
int		_vector_refcount(SV* self);
SV*		map(SV* self);
SV*		output_dim(SV* self);
